[tool.poetry]
name = "favorita-grocery-sales"
version = "0.1.0"
description = "Favorita Grocery Sales Forecasting"
authors = ["Unknown <unknown@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
pandas = ">=2.0.0"
numpy = ">=1.24.0"
scikit-learn = "*"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.0.0"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"
